apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog
          ports:
            - containerPort: 1025 # SMTP
            - containerPort: 8025 # HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  type: NodePort
  selector:
    app: mailhog
  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
      nodePort: 30125
    - name: http
      protocol: TCP
      port: 8025
      targetPort: 8025
      nodePort: 30825

